alias: Outputlink speed 1
trigger:
  - platform: state
    entity_id: binary_sensor.speed1
    to: 'on'
    for:
      seconds: 2
  - platform: state
    entity_id: binary_sensor.speed1
    to: 'off'
    for:
      seconds: 2
action:
  - service_template: >
      switch.turn_{{ trigger.to_state.state}}
    entity_id: switch.o1