- alias: Turn on living roomlight if after sunset, TV not in use, and no motion for past hour
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
      after_offset: "01:00:00"
    - condition: template
      value_template: "{% if not is_state('media_player.living_room_tv', 'playing') %}true{% endif %}"
    - condition: template
      value_template: "{% if not is_state('media_player.living_room_tv', 'paused') %}true{% endif %}"
    - condition: state
      entity_id: light.living_room
      state: 'off'
      for:
        hours: 1
  action:
  - service: homeassistant.turn_on
    data template:
       entity_id: light.living_room
       brightness: 30