version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./../:/projects
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_enable=On remote_connect_back=On"

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - .././:/projects
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/vhosts:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mariadb
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iav2
      MYSQL_USER: iav2
      MYSQL_PASSWORD: iav2

  myadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - 8000:80
      restart: always
      depends_on:
        - db