---
alias: Unlock Front Door and Garage
trigger:
  - platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
action:
  - service: lock.unlock
    data:
      entity_id: lock.front_door_locked
  - service: cover.open_cover
    data:
      entity_id: cover.garage_door_opener
---
alias: Lock Front Door
trigger:
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: group.friends
    from: 'home'
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.family
      state: 'not-home'
    - condition: state
      entity_id: group.friends
      state: 'not-home'
action:
  - service: lock.lock
    data:
      entity_id: lock.front_door_locked