---
- hosts: kvms
  vars:
    vlanon:
      bond0:
        vlans:
          - 2001
          - 2091
          - 2099
      br0: 
        vlans:
          - 62
          - 63
  tasks:
    - name: vlans per bridge
      debug: msg="device {{ item.0 }} vlan {{ item.1 }}"
      with_subelements:
        - "{{ vlanon }}"
        - vlans