version: '3'

services:
    db:
     image: mysql:5.6
     container_name: test-mysql
     restart: always
     networks:
       sqlnet:
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: demo
       MYSQL_USER: demo_user
       MYSQL_PASSWORD: demo_pass

    app:
     depends_on:
       - db
     container_name: test-app
     image: algoncharov/crudtest:latest
     networks:
       sqlnet:
     ports:
       - "80:8080"
networks:
    sqlnet: