version: "2"
services:
  order-service:
    image: registry.gitlab.com/cycle36/order-service:prototype
    ports:
      - "8080:8080"
      - "5005:5005"
    links:
      - db
      - rabbitmq
      - parking-service
    environment:
      - POSTGRES_URL=db:5432/ordersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CYCLE_PARKING_URL=http://parking-service:8082
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  integration-service:
    image: registry.gitlab.com/cycle36/integration-service:master
    restart: always
    ports:
      - "8081:8080"
    links:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  parking-service:
    image: registry.gitlab.com/cycle36/cycle-parking-service:master
    links:
      - parking-db
      - rabbitmq
    ports:
      - "8082:80"
    environment:
      DATABASE_URL: postgresql://parking-user:parking-password@parking-db:5432/parking
      RABBITMQ_HOST: rabbitmq
      FLASK_DEBUG: 1

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  db:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - orders-db-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ordersdb

  parking-db:
    image: postgres
    restart: always
    ports:
      - "15432:15432"
    volumes:
      - parking-db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: parking-user
      POSTGRES_PASSWORD: parking-password
      POSTGRES_DB: parking

volumes:
  orders-db-vol:
  parking-db-vol: