version: '2'

services:

  couchdb-peer1.org1:
    container_name: couchdb-peer1.org1
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    network_mode: bridge
    hostname: couchdb-peer1.org1
    environment:
      - DB_URL=http://localhost:5984/member_db
      - COUCHDB_USER=blockchain #TODO
      - COUCHDB_PASSWORD=pass #TODO
    ports: 
      - "5984"

  peer1.org1:
    container_name: peer1.org1
    image: hyperledger/fabric-peer:x86_64-1.1.0-preview
    depends_on:
      - "couchdb-peer1.org1"
    network_mode: bridge
    hostname: peer1.org1
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_GRPC=debug
      - CORE_LOGGING_PEER_GOSSIP=debug
      #- CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true #True
      - CORE_PEER_GOSSIP_ORGLEADER=false #false
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1:7051
      #- CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org1
      - CORE_PEER_ADDRESS=peer1.org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1:7051
      - CORE_PEER_LOCALMSPID=org1
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer1.org1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=blockchain
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass #TODO
    volumes:
      - /var/run/:/host/var/run/
      - /opt/gopath/bc1st/fabric/run/keyfiles/org1/peers/peer1.org1:/etc/hyperledger/fabric
      - /opt/gopath/bc1st/fabric/run/keyfiles:/etc/hyperledger/allorgs
    command: peer node start