---
- name: "Deploy lastest version of call center on W1"
  hosts: all
  user: root
  vars:
    destination_path: "/var/www/apps/secure/lufa"
 
  tasks:
#  - name: "Pull lastest version of master"
#    become: true
#    become_user: www-data
#    git: repo=ssh://git@bitbucket.org/lufadev/lufa-developement.git dest={{ destination_path }} version=master accept_hostkey=true
   - name: yiiconsole db migrations
     expect: 
       chdir: /home/g.shapiro/apps/geoff.lufa.com/lufa
       command: php yiiconsole.php migrate
       responses: 
         'Apply the above migration\? \(yes\|no\) \[no\]\:': "yes"
       timeout: 30
       echo: yes