- platform: template
  sensors:
    pool_temperature:
      friendly_name: Zwembad
      unit_of_measurement: ' °C'
      value_template: >
        {%- if states.input_boolean.test_mode.state == 'on' -%}
          {%- if states.input_number.test_pool_temperature.state | float == 85.0 or states.input_number.test_pool_temperature.state | float == -55.0 -%}
            {{ states.sensor.pool_temperature.state | float }}
          {%- else -%}
            {{ states.input_number.test_pool_temperature.state }}
          {%- endif -%}
        {%- else -%}
          {%- if states.sensor.input_pool_temperature.state | float == 85.0 or states.sensor.input_pool_temperature.state | float == -55.0 -%}
            {{ states.sensor.pool_temperature.state | float }}
          {%- else -%}
            {{ states.sensor.input_pool_temperature.state }}
          {%- endif -%}
        {%- endif -%}