# Example configuration.yaml entry
automation:
 - alias: 'Internet Speed Glow Connect Great' 
    trigger: 
      platform: template
      value_template: '{{ states.sensor.speedtest_download.state|float > 10}}'
    action:      
      service: shell_command.green
  - alias: 'Internet Speed Glow Connect Poor' 
    trigger: 
      platform: template
      value_template: '{{ states.sensor.speedtest_download.state| float < 10 }}' 
    action:      
      service: shell_command.red