apiVersion: v1
kind: Service
metadata:
  labels:
    name: proxystage
  name: proxystage
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    name: proxystage
status:
  nodePort: {}